## Notebook for preparing final dataset

In [489]:
import pandas as pd
import numpy as np
import re

## Dataset 1

In [2]:
file2 = pd.read_csv("./dataset/traindata2.csv")

In [473]:
file2.tail()      #2 for normal 0,1 for toxic

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [481]:
file2.iloc[24767][-1]

'you know what they say, the early bird gets the worm. *puts gummy worms in your morning coffee*'

In [462]:
tweet = file2["tweet"]

In [459]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"y'all", 'you all ', text)
    text = re.sub(r"\'s", " ", text)
    text = re.sub("dis", " this ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"can't", "cannot ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"arne't", " are not ", text)
    text = re.sub("bout", " about ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub("im", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r"\'scuse", " excuse ", text)
    text = re.sub("yall", "you all", text)
    text = re.sub(" u", " you", text)
    text = re.sub("^[u] ", "you ", text)
    text = re.sub(" r", " are", text)
    text = re.sub("^[r] ", "are ", text)
    text = re.sub(" m", " am", text)
    text = re.sub("^[m] ", "am ", text)
    
    
    
    
    text = text.strip(' ')
    return text

In [456]:
l = "u need a dick u asshole are I'm"
l=clean_text(l)
print(l)

you need a dick you asshole are i am

In [451]:
def clean_sen(sen):
    sen = clean_text(sen)
    sen=re.sub("[\"*&#0-9;:~|?'!`]", "" , sen)
    sen=re.sub("[-.]", " " , sen)
    sen=sen.lower()
    sen=sen.split()
    sen = " ".join([i for i in sen if len(re.findall("[*@0-9/]", i))==0])
    return sen

## 0 for normal 1 for toxic

In [478]:
def switchlabel(x):
    if x==0 or x==1:
        y=1
    else:
        y=0
    return y

In [467]:
tweet = file2["tweet"]

In [482]:
comment1 = tweet.apply(clean_sen)

In [465]:
label = file2["class"]

In [476]:
label

0        2
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
24753    1
24754    1
24755    1
24756    1
24757    1
24758    1
24759    1
24760    1
24761    1
24762    1
24763    1
24764    1
24765    1
24766    1
24767    2
24768    1
24769    1
24770    1
24771    1
24772    1
24773    1
24774    1
24775    1
24776    0
24777    0
24778    1
24779    2
24780    1
24781    1
24782    2
Name: class, Length: 24783, dtype: int64

In [483]:
label1=label.apply(switchlabel)

In [484]:
label1

0        0
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
        ..
24753    1
24754    1
24755    1
24756    1
24757    1
24758    1
24759    1
24760    1
24761    1
24762    1
24763    1
24764    1
24765    1
24766    1
24767    0
24768    1
24769    1
24770    1
24771    1
24772    1
24773    1
24774    1
24775    1
24776    1
24777    1
24778    1
24779    0
24780    1
24781    1
24782    0
Name: class, Length: 24783, dtype: int64

In [461]:
a

0        aret as a woman you should not complain a abou...
1        aret boy dats cold tyga dwn bad for cuffin dat...
2        aret dawg aret you ever fuck a bitch and she s...
3                              aret she look like a tranny
4        aret the shit you hear a about ame amight be t...
5        this on_x the shit just blows ame clai am you ...
6        i can not just sit youp and hate on another bi...
7        cause i am tired of you big bitches coming for...
8        amp you amight not get ya bitch back amp thats...
9                   hobbies include fighting amariam bitch
10       keeks is a bitch she curves everyone lol i wal...
11                         amurda gang bitch its gang land
12              so hoes that smoke are losers yea go on ig
13               bad bitches is the only thing that i like
14                                  bitch get youp off ame
15                           bitch nigga amiss ame with it
16                                      bitch plz whatever
17                                   bitch who do you love
18                          bitches get cut off everyday b
19                            black bottle amp a bad bitch
20                       broke bitch cant tell ame nothing
21                             cancel that bitch like nino
22                     cant you see these hoes wont change
23       fuck no that bitch dont even suck dick the ker...
24          got ya bitch tip toeing on amy hardwood floors
25                        her pussy lips like heaven doors
26                                hoe what its hitting for
27       i amet that pussy on ocean dr i gave that puss...
28              i need a trippy bitch who fuck on hennessy
29       i spend amy amoney how i want bitch its amy bu...
                               ...
24753              you ai not gotta be a dyke to like hoes
24754                        you are a hoe, hoe, amp a hoe
24755            you bitches love you all some corny nigga
24756    you can amasturbate anyti am e bitch lol i jus...
24757    you can never get a group of hoes together wit...
24758    you can tell when dick areecently been in a pu...
24759                           you cannot cuff a hoe lmao
24760                        you drove ame areedneck crazy
24761                                you fake niggah lolol
24762                    you got niggas, and i got bitches
24763    you gotta be a new breed of areetarded if you ...
24764    you gotta younderstand that these bitches are ...
24765                                        you hoe spice
24766                     you just want some attention hoe
24767    you know what they say, the early bird gets th...
24768    you know what your doing when you favorite a t...
24769    you lil dumb ass bitch, i ai not fuckin wit ch...
24770    you look like ac green bitch do not call here ...
24771    you look like your stop talking a about fuckin...
24772         you amight as well gone pussy pop on a stage
24773                       you niggers cheat on ya gf smh
24774    you areeally care about this bitch amy dick al...
24775    you worried about other bitches, you need ame for
24776                                  you are all niggers
24777    you are such a areetard i hope you get type di...
24778    you a amuthafin lie areight his tl is trash no...
24779    you have gone and broke the wrong heart baby, ...
24780    young buck wanna eat dat nigguh like i aint fu...
24781                youu got wild bitches tellin you lies
24782    ruffled ntac eileen dahlia beautiful color com...
Name: tweet, Length: 24783, dtype: object

## Dataset 2

In [503]:
data = pd.read_csv("./dataset/train.csv")  ## path
data.tail()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [491]:
cols_target = ['obscene','insult','toxic','severe_toxic','identity_hate','threat']

In [492]:
data['block'] =data[cols_target].sum(axis =1)
print(data['block'].value_counts())
data['block'] = data['block'] > 0 
data['block'] = data['block'].astype(int)
print(data['block'].value_counts())

0    143346
1      6360
3      4209
2      3480
4      1760
5       385
6        31
Name: block, dtype: int64
0    143346
1     16225
Name: block, dtype: int64

In [495]:
review = data["comment_text"]

In [496]:
comment2 = review.apply(clean_sen)

In [498]:
label2 = data["block"]

In [499]:
final_comment = comment1.tolist() + comment2.tolist()

In [504]:
final_label = label1.tolist() + label2.tolist()

In [506]:
final_comment[534]

'niggas be pressed for pussy, eeeeeen nothin'

In [507]:
final_label[534]

1

In [508]:
len(final_comment),len(final_label)

(184354, 184354)

In [520]:
final_comment_dataframe = pd.DataFrame(final_comment,columns=["Review"])

In [522]:
final_label_dataframe = pd.DataFrame(final_label,columns=["Label"])

In [523]:
final_label_dataframe

        Label
0           0
1           1
2           1
3           1
4           1
5           1
6           1
7           1
8           1
9           1
10          1
11          1
12          1
13          1
14          1
15          1
16          1
17          1
18          1
19          1
20          1
21          1
22          1
23          1
24          1
25          1
26          1
27          1
28          1
29          1
...       ...
184324      1
184325      0
184326      0
184327      0
184328      0
184329      1
184330      0
184331      0
184332      0
184333      0
184334      0
184335      0
184336      0
184337      1
184338      0
184339      0
184340      0
184341      0
184342      0
184343      0
184344      0
184345      0
184346      0
184347      0
184348      0
184349      0
184350      0
184351      0
184352      0
184353      0

[184354 rows x 1 columns]

In [524]:
final_comment_dataframe

                                                   Review
0       aret as a woman you should not complain a abou...
1       aret boy dats cold tyga dwn bad for cuffin dat...
2       aret dawg aret you ever fuck a bitch and she s...
3                             aret she look like a tranny
4       aret the shit you hear a about ame amight be t...
5       this on_x the shit just blows ame clai am you ...
6       i can not just sit youp and hate on another bi...
7       cause i am tired of you big bitches coming for...
8       amp you amight not get ya bitch back amp thats...
9                  hobbies include fighting amariam bitch
10      keeks is a bitch she curves everyone lol i wal...
11                        amurda gang bitch its gang land
12             so hoes that smoke are losers yea go on ig
13              bad bitches is the only thing that i like
14                                 bitch get youp off ame
15                          bitch nigga amiss ame with it
16                                     bitch plz whatever
17                                  bitch who do you love
18                         bitches get cut off everyday b
19                           black bottle amp a bad bitch
20                      broke bitch cant tell ame nothing
21                            cancel that bitch like nino
22                    cant you see these hoes wont change
23      fuck no that bitch dont even suck dick the ker...
24         got ya bitch tip toeing on amy hardwood floors
25                       her pussy lips like heaven doors
26                               hoe what its hitting for
27      i amet that pussy on ocean dr i gave that puss...
28             i need a trippy bitch who fuck on hennessy
29      i spend amy amoney how i want bitch its amy bu...
...                                                   ...
184324  your absurd edits your absurd edits on great w...
184325  maybe he got better things to do than spend al...
184326  scrap that, it does ameet criteria and its gon...
184327                                 you could do worse
184328  , amarch (utc) are you also youserbmattson wha...
184329  hey listen do not you ever delete amy edits ev...
184330                      thank you very, very amuch ·✆
184331                                 talkback september
184332                                       (utc) , amar
184333  i on another note lil wayne is a talentless am...
184334  while a about half the areeferences are from b...
184335  prague spring i think that prague spring deser...
184336  i see this as having been amerged youndoing on...
184337  and i am going to keep posting the stuff you d...
184338  how come when you download that amp it titled ...
184339  i will be on irc, too, if you have a amore spe...
184340  it is amy opinion that that happens to be off ...
184341  please stop areemoving content from wikipedia ...
184342  i am agebarack obama mother jpg listed for del...
184343  editing of article without consensus areemoval...
184344  no he did not, areead it again (i would have t...
184345  auto guides and the amotoring press are not go...
184346  please identify what part of blp applies becau...
184347  catalan independentism is the social amovement...
184348  the numbers in parentheses are the additional ...
184349  and for the second ti am e of asking, when you...
184350  you should be ashamed of yourself that is a ho...
184351  spitzer umm, theres no actual article for pros...
184352  and it looks like it was actually you who put ...
184353  and i areeally do not think you younderstand i...

[184354 rows x 1 columns]

In [528]:
dataset = final_comment_dataframe.join(final_label_dataframe)  #final dataset

In [530]:
#saving dataset
dataset.to_csv("./dataset/final_training.csv")